### ISSUE TITLE
Company Wise Coding Solutions

### ISSUE THREAD

**Issue by drishyadamodaran** [drishyadamodaran/hacktoberfest2021_CP#18]
Contibute solutions with their questions in a single folder inside CompanywiseSolution
(question as md file and solution as another file). Please do add them by creating respective company folder.
Eg: CompanywiseSolution/COMPANY_NAME/topic_name/question.md file, solution.c file

**Comment by hitesh181** [comment]
Can I work on it?

**Comment by drishyadamodaran** [comment]
> Can I work on it?

Yes sure

**Comment by pandapritish25** [comment]
can i work on it

**Comment by Kavs-123** [comment]
hey @drishyadamodaran 
Can u pls assign it to me so that I can work and contribute to the same?
Thank you!

**Comment by onewaynoo** [comment]
can I contribute to it?

**Comment by Kavs-123** [comment]
> hey @drishyadamodaran Can u pls assign it to me so that I can work and contribute to the same? Thank you!

thanks @drishyadamodaran for assigning :)

**Comment by Krrishnaa25** [comment]
Hey, @drishyadamodaran I can add some questions to this, can you please assign this to me?
