### ISSUE TITLE
MergeSort code in different languages

### ISSUE THREAD

**Issue by drishyadamodaran** [drishyadamodaran/hacktoberfest2021_CP#2]
Contribute to the folder Algorithms.

**Comment by gaurangisinha** [comment]
Hi, @drishyadamodaran.Can I contribute to this repository in Python?

**Comment by drishyadamodaran** [comment]
> Hi, @drishyadamodaran Can I contribute to this repository in Python?

yes u can

**Comment by imsushant12** [comment]
hi, @drishyadamodaran  Can I contribute in C++?

**Comment by drishyadamodaran** [comment]
> hi, @drishyadamodaran Can I contribute in C++?

Yeah sure

**Comment by a-ayush19** [comment]
@drishyadamodaran can you assign this to me, I wanna contribute in JavaScript

**Comment by arunim-iiitlCS** [comment]
I can contribute a java code please assign me this.

Regards

**Comment by drishyadamodaran** [comment]
> @drishyadamodaran can you assign this to me, I wanna contribute in JavaScript

Yeah sure

**Comment by drishyadamodaran** [comment]
> I can contribute a java code please assign me this.
> 
> Regards

Yeah sure. It's open for all.

**Comment by a-ayush19** [comment]
@drishyadamodaran kindly have a look at #25 
thank you

**Comment by hitesh181** [comment]
Hey I'm a beginner at Github but have worked with Java before, Can you please assign this to me so I explore it further?

**Comment by arunim-iiitlCS** [comment]
> > I can contribute a java code please assign me this.
> > Regards
> 
> Yeah sure. It's open for all.

Please see PR #26

**Comment by Richa-15** [comment]
Hi,
Please assign this issue to me. I would like to upload solution in c++

**Comment by srishti1302** [comment]
HI
I would like to contribute in java.Please assign this to me

**Comment by drishyadamodaran** [comment]
> HI I would like to contribute in java.Please assign this to me
Done

**Comment by drishyadamodaran** [comment]
> Hi, Please assign this issue to me. I would like to upload solution in c++

Done

**Comment by drishyadamodaran** [comment]
> > > I can contribute a java code please assign me this.
> > > Regards
> > 
> > 
> > Yeah sure. It's open for all.
> 
> Please see PR #26
> 
> Thanks

Approved

**Comment by drishyadamodaran** [comment]
> @drishyadamodaran kindly have a look at #25 thank you

Approved

**Comment by drishyadamodaran** [comment]
> Hey I'm a beginner at Github but have worked with Java before, Can you please assign this to me so I explore it further?

Carry on
