### ISSUE TITLE
Coding solutions of Arrays in different languages

### ISSUE THREAD

**Issue by drishyadamodaran** [drishyadamodaran/hacktoberfest2021_CP#3]

**Comment by YushChaudhary** [comment]
Can you explain more. Thanks

**Comment by drishyadamodaran** [comment]
> Can you explain more. Thanks

You can add Solutions for coding questions based on array

**Comment by YushChaudhary** [comment]
ok can you assign this issue to me thanks.

**Comment by drishyadamodaran** [comment]
@YushChaudhary  Ok do it.

**Comment by YushChaudhary** [comment]
thanks

**Comment by drishyadamodaran** [comment]
Dont forget to give a star

**Comment by YushChaudhary** [comment]
Sure

**Comment by shweta-kansal** [comment]
Hey Can I add solution for Kth largest element in an array using cpp . kindly assign this issue to me.

**Comment by YushChaudhary** [comment]
#7  This is one code for today i will continue contributing, Don't forget to label my issue as hacktoberfest so i can mark my contribution thanks. and i add a start to your lovely repo.

**Comment by 0901IT201046** [comment]
Hello. I have made my PR #12. Please reveiw and merge it.
Thankyou.

**Comment by drishyadamodaran** [comment]
@YushChaudhary Yeah done
@0901IT201046 done
@shweta-kansal  yes you can

**Comment by ApoorvaKaushal09** [comment]
Hey can I add solution for finding duplicates in an array in java?
Please assign it to me.

**Comment by drishyadamodaran** [comment]
> Hey can I add solution for finding duplicates in an array in java? Please assign it to me.

Yeah sure. Start contributing!! It's assigned to all.

**Comment by rutuja206** [comment]
Hey can I add solution for maximum subarray sum solution in C++?
Please assign it to me.

**Comment by drishyadamodaran** [comment]
> Hey can I add solution for maximum subarray sum solution in C++? Please assign it to me.

Carry on!!

**Comment by RajdeepOfGithub** [comment]
Hey!... can I contribute in adding the code of a histogram of an array in C++ ?

**Comment by VishalSehgal525** [comment]
I would like to contribute to this repo using C/C++ and JavaScript codes for an array.
